apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeege-iptables
  labels:
    k8s-app: kubeedge
    kubeedge: iptables-set
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: iptables-set
subjects:
  - kind: ServiceAccount
    name: kubeedge-iptables